name: Test

on: push

jobs:
  run-linters:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: yarn
          cache-dependency-path: './yarn.lock'

      - name: Run application in dev
        run: yarn dev

      - name: Run tests
        run: yarn test
